# Generated by Django 5.0.6 on 2026-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_download', models.FloatField(default=0)),
                ('avg_upload', models.FloatField(default=0)),
                ('avg_latency', models.FloatField(default=0)),
                ('avg_quality_score', models.FloatField(default=0)),
                ('network_tests_count', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('courses_active', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_user_snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
