# Generated by Django 5.0.6 on 2026-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField(help_text='Download speed in Mbps')),
                ('upload_speed', models.FloatField(help_text='Upload speed in Mbps')),
                ('latency', models.FloatField(help_text='Latency in milliseconds')),
                ('jitter', models.FloatField(default=0.0, help_text='Jitter in milliseconds')),
                ('packet_loss', models.FloatField(default=0.0, help_text='Packet loss percentage')),
                ('connection_type', models.CharField(choices=[('wifi', 'WiFi'), ('mobile', 'Mobile Data'), ('ethernet', 'Ethernet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('isp', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('quality_score', models.FloatField(default=0.0)),
                ('test_server', models.CharField(blank=True, default='', max_length=200)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'network_measurements',
                'ordering': ['-created_at'],
            },
        ),
    ]
