# Generated by Django 5.0.6 on 2026-02-24 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmeasurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='networkmeasurement',
            index=models.Index(fields=['user', '-created_at'], name='network_mea_user_id_8495ce_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmeasurement',
            index=models.Index(fields=['city', 'country'], name='network_mea_city_b6f637_idx'),
        ),
    ]
